VERIFIER_EVIDENCE_PREFIX = "verifier."
VERIFIER_NAMED_CHECK_EVIDENCE_TYPE = "verifier.github.named_check"

NAMED_CHECK_MAX_ASSERTIONS = 32
NAMED_CHECK_MAX_AC_ID_LENGTH = 100
NAMED_CHECK_MAX_REPOSITORY_LENGTH = 300
NAMED_CHECK_MAX_HEAD_SHA_LENGTH = 64
NAMED_CHECK_MAX_CHECK_NAME_LENGTH = 200
NAMED_CHECK_MAX_RUN_ID_LENGTH = 100
NAMED_CHECK_MAX_REFERENCE_LENGTH = 2000
NAMED_CHECK_MAX_IDEMPOTENCY_KEY_LENGTH = 200
NAMED_CHECK_MAX_ASSERTION_NAME_LENGTH = 100
NAMED_CHECK_MAX_ASSERTION_VALUE_LENGTH = 1024
NAMED_CHECK_MAX_INTEGER_ABS = 2**63 - 1
